name: Playwright Tests
on: push

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    # Update env variables with your own database credentials
    env:
      PGHOST: localhost
      PGDATABASE: next_js_example_fall_2022
      PGUSERNAME: next_js_example_fall_2022
      PGPASSWORD: next_js_example_fall_2022

    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER next_js_example_fall_2022 PASSWORD 'next_js_example_fall_2022'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=next_js_example_fall_2022 next_js_example_fall_2022
      - uses: actions/checkout@v3
      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: yarn playwright install --with-deps

      - name: Build localhost
        run: yarn build
      - name: Run tests
        run: yarn playwright test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-screenshots-videos
          path: playwright/test-results/
